version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    platform: linux/amd64
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    platform: linux/amd64
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.7.2
    depends_on:
      - postgres
      - airflow-init
      - kafka
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
     #AIRFLOW__CORE__FERNET_KEY: ''
      #AIRFLOW__WEBSERVER__SECRET_KEY: ''
      AIRFLOW__LOGGING__BASE_LOG_FOLDER: /opt/airflow/logs
      AIRFLOW__LOGGING__WORKER_LOG_SERVER_PORT: 8793
    volumes:
      - ./:/opt/Weather_ML
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/requirements.txt:/opt/airflow/requirements.txt
      - ./airflow/logs:/opt/airflow/logs
      - ./snowflake_utils:/opt/Weather_ML/snowflake_utils
      - ./data:/opt/Weather_ML/data
      - ./dbt:/opt/dbt
      - ~/.dbt:/home/airflow/.dbt
      - ./keys:/opt/airflow/keys
      - ./airflow/.env:/opt/airflow/.env

    user: "${AIRFLOW_UID:-50000}:0"

    command: bash -c "pip install -r requirements.txt && airflow webserver"


  airflow-scheduler:
    image: apache/airflow:2.7.2
    depends_on:
      - postgres
      - kafka
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      #AIRFLOW__CORE__FERNET_KEY: 'your_fernet_key_here'
      AIRFLOW__LOGGING__BASE_LOG_FOLDER: /opt/airflow/logs
      AIRFLOW__LOGGING__WORKER_LOG_SERVER_PORT: 8793

    volumes:
      - ./:/opt/Weather_ML
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/requirements.txt:/opt/airflow/requirements.txt
      - ./airflow/logs:/opt/airflow/logs
      - ./snowflake_utils:/opt/Weather_ML/snowflake_utils
      - ./data:/opt/Weather_ML/data
      - ./dbt:/opt/dbt
      - ~/.dbt:/home/airflow/.dbt
      - ./keys:/opt/airflow/keys
      - ./airflow/.env:/opt/airflow/.env

    user: "${AIRFLOW_UID:-50000}:0"
    command: bash -c "pip install -r requirements.txt && airflow scheduler"

  airflow-init:
    image: apache/airflow:2.7.2
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      # AIRFLOW__CORE__FERNET_KEY: 'your_fernet_key_here'

    volumes:
      - ./:/opt/Weather_ML
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./snowflake_utils:/opt/Weather_ML/snowflake_utils



    entrypoint: >
      bash -c "
        pip install -r /opt/airflow/requirements.txt &&
        airflow db init &&
        airflow users create --username admin --firstname Airflow --lastname Admin --role Admin --email admin@example.com --password admin
      "

  dbt:
    build:
      context: .
      dockerfile: Dockerfile.dbt
    volumes:
      - ./dbt:/usr/app/dbt
      - ./dbt/profiles/profiles.yml:/root/.dbt/profiles.yml
    working_dir: /usr/app/dbt
    entrypoint: ["sleep", "infinity"]

  api-producer:
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - ./kafka:/app/kafka
    working_dir: /app/kafka/producers
    entrypoint: ["python", "api_producer.py"]

volumes:
  postgres_data:
