FROM apache/airflow:2.8.1-python3.11

# Set working directory
WORKDIR /opt/airflow

# Install dbt core and desired adapter (choose your adapter)
RUN pip install --no-cache-dir dbt-core dbt-postgres

# Optional: Copy your dbt project into image (not needed if you use bind mounts)
# COPY dbt /opt/dbt

# Optional: Install other Python dependencies
# COPY requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt
