dbt_weather:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ZFLRNBO-YT37108
      user: DBT_USER_DAT
      password: dat18101993
      role: ACCOUNTADMIN
      database: KAFKA_AIRFLOW_WEATHER
      schema: WEATHER_ANALYTICS
      threads: 4
      client_session_keep_alive: false