name: dbt CI

on:
  pull_request:
    branches: [ main ]

jobs:
  dbt-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: dbt

    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_ROLE: "USER_DBT_ROLE"
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      SNOWFLAKE_CI_USER: ${{ secrets.SNOWFLAKE_CI_USER }}
      SNOWFLAKE_CI_USER_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_CI_USER_PRIVATE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Ensure dbt profiles directory exists
        run: mkdir -p ~/.dbt

      - name: Create profiles.yml
        run: |
          cat <<EOT > ~/.dbt/profiles.yml
          dbt_weather:
            outputs:
              ci:
                type: snowflake
                account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
                user: ${{ secrets.SNOWFLAKE_CI_USER }}
                private_key: ${{ secrets.SNOWFLAKE_CI_USER_PRIVATE_KEY }}
                role: USER_DBT_ROLE
                warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
                database: ${{ secrets.SNOWFLAKE_DATABASE }}
                schema: ${{ secrets.SNOWFLAKE_SCHEMA }}
            target: ci
          EOT

      - name: Install dbt & sqlfluff
        run: |
          pip install dbt-core dbt-snowflake sqlfluff
          pip install sqlfluff-templater-dbt
          dbt deps

      - name: Lint SQL files
        run: sqlfluff lint . --dialect snowflake

      - name: Debug dbt setup
        run: dbt debug

      - name: Run dbt build
        run: dbt build --target ci