name: dbt CD
on:
  release:
    types: [created]

jobs:
  dbt-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dbt and dependencies
        run: |
          pip install -r requirements.txt
          # Only run dbt deps inside dbt folder
          cd dbt
          dbt deps

      - name: Set up dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          pwd
          cp .dbt/profiles-cicd.yml ~/.dbt/profiles.yml
          ls -la ~/.dbt
        working-directory: dbt

      - name: Deploy dbt models
        run: dbt build --target prod
        working-directory: ./dbt
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}_${{ github.event.number }}
          SNOWFLAKE_CI_USER: ${{ secrets.SNOWFLAKE_CI_USER }}
          SNOWFLAKE_CI_USER_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_CI_USER_PRIVATE_KEY }}
          SNOWFLAKE_CD_USER: ${{ secrets.SNOWFLAKE_CD_USER }}
          SNOWFLAKE_CD_USER_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_CD_USER_PRIVATE_KEY }}
