name: dbt CI

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  dbt-test:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_ROLE: "USER_DBT_ROLE"
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      SNOWFLAKE_CI_USER: ${{ secrets.SNOWFLAKE_CI_USER }}
      SNOWFLAKE_CI_USER_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_CI_USER_PRIVATE_KEY }}
      SNOWFLAKE_CI_USER_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_CI_USER_PRIVATE_KEY_PASSPHRASE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Set up uv virtualenv
        run: uv venv

      - name: Install Python deps
        run: uv pip install -r pyproject.toml

      - name: Install dbt & sqlfluff
        run: |
          uv pip install dbt-core dbt-snowflake sqlfluff
          uv pip install sqlfluff-templater-dbt

      - name: set up profiles.yml
        run: |
            mkdir -p ~/.dbt
            pwd
            cp .dbt/profiles-cicd.yml ~/.dbt/profiles.yml
            ls -la ~/.dbt
        working-directory: dbt

      - name: Run pylint
        run: uv run pylint . --fail-under=8.0

      - name: Install dbt packages
        run: uv run dbt deps --target ci
        working-directory: dbt

      - name: Lint SQL files
        run: uv run sqlfluff lint .
        working-directory: dbt

      - name: Clean DBT Artifacts
        run: uv run dbt clean --target ci
        working-directory: dbt

      - name: Install dbt packages
        run: uv run dbt deps --target ci
        working-directory: dbt

      - name: compile dbt models
        env:
          SNOWFLAKE_CI_USER_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_CI_USER_PRIVATE_KEY }}
          SNOWFLAKE_CI_USER_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_CI_USER_PRIVATE_KEY_PASSPHRASE }}
        run: uv run dbt compile --target ci
        working-directory: dbt

      - name: Run dbt build
        run: uv run dbt build --target ci
        working-directory: dbt

