name: dbt CD
on:
  release:
    types: [created]

jobs:
  dbt-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dbt and dependencies
        run: |
          pip install -r requirements.txt
          # Only run dbt deps inside dbt folder
          cd dbt
          dbt deps

      - name: Deploy dbt models
        run: dbt build --target prod
        working-directory: ./dbt
