name: dbt CI

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  dbt-test:
    runs-on: ubuntu-latest


    env:
      DBT_PROFILES_DIR: ./profiles
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_ROLE: "USER_DBT_ROLE"
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      SNOWFLAKE_CI_USER: ${{ secrets.SNOWFLAKE_CI_USER }}
      SNOWFLAKE_CI_USER_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_CI_USER_PRIVATE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dbt & sqlfluff & install pylint .
        run: |
          pip install dbt-core dbt-snowflake sqlfluff
          pip install sqlfluff-templater-dbt
          pip install pylint

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Set up uv virtualenv
        run: uv venv

      - name: Install Python deps
        run: uv pip install

      - name: Run pylint
        run:
          pylint . --fail-under=8.0

      - name: Install dbt packages
        run: dbt deps --target ci

      - name: Lint SQL files
        run: sqlfluff lint . --dialect snowflake

      - name: Clean DBT Artifacts
        run: dbt clean --target ci

      - name: Install dbt packages
        run: dbt deps --target ci

      - name: compile dbt models
        run: dbt compile --target ci

      - name: Run dbt build
        run: dbt build --target ci

